import keyMirror from 'key-mirror';

export default keyMirror({
    LOGIN: null,
    TOKEN: null,
    VCODE: null,
    LOGOUT: null,
    CLOSE: null,
    ISCORP: null,
    
    WECHAT_LOGIN: null,
    APPLE_LOGIN: null,
    BIND_MOBILE: null,
    SWITCH_CARD: null,

    CONFIG: null,
    CONFIG_OSS: null,
    CONFIG_AD: null,
    CONFIG_POP_AD: null,
    CONFIG_GROUP_AD: null,
    CONFIG_CATEGORY_ASK: null,
    CONFIG_CATEGORY_COURSE: null,
    CONFIG_CATEGORY_FEEDBACK: null,
    CONFIG_GIFT: null,
    CONFIG_RECHARGE: null,
    CONFIG_TIP: null,

    SITE_INDEX: null,
    SITE_CHANNEL: null,
    SITE_COMMENT: null,
    SITE_UPLOAD: null,
    SITE_UPLOADS:null,

    SITE_SEARCH: null,
    SITE_SEARCH_HISTORY: null,
    SITE_SEARCH_CLEAR: null,
    SITE_SEARCH_CLEARALL: null,
    
    COURSE_INDEX: null,
    COURSE_RECOMM: null,
    COURSE_LIVE: null,
    COURSE_LIVE_STAT: null,
    COURSE_PLAYBACK: null,
    COURSE_INFO: null,
    COURSE_COMMENT: null,
    COURSE_VERIFY: null,
    COURSE_SCORE: null,
    COURSE_GOODS: null,
    COURSE_GOODS_SHARE: null,
    

    COURSE_MAP: null,
    COURSE_MAP_INFO: null,
    COURSE_LEVEL_STATUS: null,

    EXAM_REVIEW: null,
    EXAM_TEST: null,
    EXAM_USER: null,
    EXAM_MUST: null,
    EXAM_USER_WRONG: null,
    EXAM_INFO: null,
    EXAM_ANSWER: null,

    STUDY_RANK: null,
    STUDY_PLAN: null,
    STUDY_PLAN_INFO: null,
    STUDY_PLAN_ACCEPT: null,
    STUDY_PLAN_STATUS: null,

    NEWS_INDEX: null,
    NEWS_SPECIAL: null,
    NEWS_INFO: null,
    NEWS_RELATION: null,
    NEWS_COMMENT: null,
    NEWS_ABOUT: null,

    ORDER_BUY: null,
    ORDER_RECHARGE: null,

    ACTIVITY_INDEX: null,
    ACTIVITY_INFO: null,
    ACTIVITY_JOIN: null,
    ACTIVITY_WORK: null,
    ACTIVITY_VOTE: null,
    ACTIVITY_USER_VOTE: null,
    ACTIVITY_PAPER: null,
    ACTIVITY_ANSWER: null,

    ACTIVITY_FLOP: null,
    ACTIVITY_FLOP_REWARD: null,
    ACTIVITY_FLOP_LOTTERY: null,
    ACTIVITY_FLOP_LOTTERY_RECEIVE: null,

    O2O_INDEX: null,
    O2O_PAY: null,
    O2O_INFO: null,
    O2O_APPLY: null,
    O2O_SIGN: null,
    
    GROUP_INDEX: null,
    GROUP_INFO: null,
    GROUP_PUBLISH: null,
    GROUP_SIGN: null,
    GROUP_COMMENT: null,
    GROUP_REPLY: null,
    GROUP_MEMBER: null,
    GROUP_ACTION: null,
    GROUP_APPLY: null,
    GROUP_EXIT: null,
    GROUP_USER: null,

    ASK_INDEX: null,
    ASK_INFO: null,
    ASK_REPLY: null,
    ASK_PUBLISH: null,
    ASK_ANSWER: null,
    ASK_RECOMM_USER: null,
    ASK_INVITE: null,
    ASK_USER_ASK: null,
    ASK_USER_ANSWER: null,

    TEACHER_INDEX: null,
    TEACHER_RECOMM: null,
    TEACHER_INFO: null,
    TEACHER_APPLY: null,
    TEACHER_APPLY_CORP: null,
    TEACHER_APPLY_INFO: null,
    TEACHER_CERT: null,

    USER: null,
    USER_ACCOUNT: null,

    USER_REMIND: null,
    USER_MESSAGE: null,
    USER_MESSAGE_UNREAD: null,
    USER_MESSAGE_OPERATE: null,

    USER_LEVEL: null,

    USER_STUDY: null,
    USER_STUDY_STAT: null,
    USER_STUDY_SYNC: null,
    USER_STUDY_ARTICLE_SYNC: null,

    USER_CREDIT: null,
    USER_INTEGRAL: null,
    USER_EXCHANGE: null,
    USER_BALANCE: null,
    USER_REWARD_INTEGRAL: null,
    USER_REWARD: null,

    USER_CERT: null,
    USER_MEDAL: null,
    
    USER_BOOK: null,
    USER_UNBOOK: null,

    USER_SHARE: null,
    USER_LOG: null,
    USER_COLLECT: null,
    USER_UNCOLLECT: null,
    USER_COLLECT_ITEM: null,
    USER_COLLECT_COURSE: null,
    
    USER_FOLLOW: null,
    USER_FOLLOW_CONTENT: null,
    USER_UNFOLLOW_CONTENT: null,
    USER_FOLLOW_TEACHER: null,
    USER_UNFOLLOW_TEACHER: null,

    USER_COMMENT: null,
    
    USER_LIKE_COMMENT: null,
    USER_UNLIKE_COMMENT: null,

    USER_LIKE_COURSE: null,
    USER_UNLIKE_COURSE: null,

    USER_COURSE: null,

    USER_TASK: null,
    USER_SQUAD: null,

    USER_ADDRESS: null,
    USER_SAVE_ADDRESS: null,
    USER_FIRST_ADDRESS: null,
    USER_REMOVE_ADDRESS: null,

    USER_FEEDBACK: null,
    FEEDBACK: null,
    RELATED_GET:null,
    LOGIN_LOG:null,
    SHAREVOD:null,
})